### PR TITLE
Finish off container and multiarch

### PR DESCRIPTION
**Pull request by CHBMB**
Had to make up some logic to grab the latest release from an RSS feed, so set Jenkins-vars to `os` but would appreciate a 2nd pair of eyes to check that will work.

Tested on x64 but `armhf` and `arm64` tags [here](https://hub.docker.com/r/chbmb/dokuwiki/tags)

### CODE REVIEW

**Comment by thelamer** [comment]
For the tagging logic you can use a custom command that runs a docker container with an xml parser installed . As it stands now it will pass a package md5 as the build arg and bomb out on download for a live build.

**Comment by thelamer** [comment]
Like this 

https://github.com/linuxserver/docker-oscam/blob/master/jenkins-vars.yml#L6

**Comment by CHBMB** [comment]
@thelamer Thanks, I've implemented that now, also updated `50-config` and added a default `.htaccess` file as I realised pretty URLs and subfolder reverse proxy support is probably a necessary requirement.

**Comment by thelamer** [comment]
Alpine does not wget by default , you should be able to run the docker command locally and witness the exact output you get

**Comment by CHBMB** [comment]
@thelamer Just updated my original post as you were typing to show the output.  Think that's working

**Comment by thelamer** [comment]
There is a busybox version of wget in the base container, learn something new everyday

**Comment by CHBMB** [comment]
I need to remove the `$APP_URL` setting.

**Pull request merged**
